achilles:
  pvcName: achilles-output
  dbSecretName: ohdsi-achilles-db-secret
  env:
    CDM_VERSION: "5.4"
    SOURCE_NAME: "ohdsi"
    CDM_SCHEMA: "omopcdm"
    VOCAB_SCHEMA: "omopcdm"
    DB_DBMS: "postgresql"
    DB_HOSTNAME: "127.0.0.1"
    DB_NAME: "omopcdm"
    DB_PORT: 5432
    JSON_EXPORT: "TRUE"
    DQD: "TRUE"
    DQD_VERBOSE: "TRUE"
    DQD_JSON_FILE: "TRUE"
    SKIP_ACHILLES: "FALSE"
